"""empty message

Revision ID: 0d686078c6a6
Revises: a315b048277f
Create Date: 2023-12-06 10:26:07.162707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d686078c6a6'
down_revision = 'a315b048277f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
